image:
  - Visual Studio 2019
clone_folder: c:\projects\source

environment:
    PYTHON: "C:\\Python38-x64\\python.exe"

build_script:
- cmd: >-
    cmake -S c:\projects\source -B ./build -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release

    cmake --build ./build --config "Release"

test_script:
- cmd: cd build && ctest -C Debug 